[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/netlify_api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
