[build]
  base = "."
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "functions"
  external_node_modules = ["mangum"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
